import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Navbar } from "@repo/ui/layout/navbar/navbar";
import { Sidebar } from "@repo/ui";
import ThemeProvider from "@repo/ui/theme-provider";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  readonly children: React.ReactNode;
}) {
  const cookieStore = cookies();

  const savedTheme = (await cookieStore).get("theme")?.value;

  const temaInicial = savedTheme === "dark" ? "dark" : "light";
  return (
    <html lang="es">
      <body className="grid min-h-dvh grid-rows-[auto_1fr_auto]">
        <ThemeProvider initialTheme={temaInicial}>
          <header>
            <Navbar />
          </header>
          <main className="flex">
            <Sidebar />
            {children}
          </main>
          <footer>footer</footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
