import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Navbar } from "@repo/ui/layout/navbar/navbar";
import { Profile, Sidebar, SidebarTrigger } from "@repo/ui";

import ThemeProvider from "@repo/ui/theme-provider";
import { cookies } from "next/headers";
import { Home, Image, Settings, Users } from "lucide-react";
import ThemeToggle from "@repo/ui/theme/dark-mode-toggle/dark-mode-toggle";
import { SidebarProvider } from "@repo/providers";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  readonly children: React.ReactNode;
}) {
  const cookieStore = cookies();

  const savedTheme = (await cookieStore).get("theme")?.value;

  const temaInicial = savedTheme === "dark" ? "dark" : "light";

  // En tu RootLayout.tsx o un archivo de configuración separado
  const sidebarLinks = [
    {
      label: "Inicio",
      href: "/",
      // Puedes usar cualquier icono de Lucide, asegúrate de importarlos arriba
      icon: <Home className="w-5 h-5" />,
    },
  ];
  return (
    <html lang="es">
      <body className="grid h-dvh grid-rows-[auto_1fr_auto]">
        <ThemeProvider initialTheme={temaInicial}>
          <SidebarProvider>
            <header>
              <Navbar >
                <div className="flex flex-row items-end justify-end">
                  <ThemeToggle />
                  <SidebarTrigger />
                  <Profile
                    image_profile={<Image />}
                    image_alt="userImage"
                    userName="nombre de usuario"
                    showUserMenu={true}
                  />
                </div>
              </Navbar>
            </header>
            <main className="flex h-full overflow-hidden">
              <div className="flex-1 overflow-y-auto">
                <Sidebar links={sidebarLinks} />
                {children}
              </div>
            </main>
            <footer>footer</footer>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
