import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import {
  Navbar,
  Profile,
  Sidebar,
  SidebarTrigger,
  ThemeProvider,
  ThemeToggle,
} from "@repo/ui";
import { cookies } from "next/headers";
import { User } from "lucide-react";
import { SidebarProvider } from "@repo/providers";

export const metadata: Metadata = {
  title: "Seguros",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  readonly children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const savedTheme = (await cookieStore).get("theme")?.value;
  const temaInicial = savedTheme === "dark" ? "dark" : "light";
  return (
    <html lang="en" className={temaInicial} data-theme={temaInicial}>
      {/* 1. Aseguramos que el body ocupe todo el alto sin scroll global */}
      <body className="h-dvh flex flex-col overflow-hidden dark:bg-black">
        <ThemeProvider initialTheme={temaInicial}>
          <SidebarProvider>
            <header className="shrink-0">
              <Navbar logo={<SidebarTrigger />}>
                <div className="flex flex-col md:flex-row items-end md:justify-end gap-4">
                  <ThemeToggle />
                  <Profile
                    image_profile={<User />}
                    image_alt="userImage"
                    userName="nombre de usuario"
                    showUserMenu={true}
                  />
                </div>
              </Navbar>
            </header>

            {/* 2. El main debe ser flex y ocupar el 100% del espacio restante */}
            <main className="flex flex-1 overflow-hidden">
              <Sidebar />
              {/* 3. El contenedor de children debe tener scroll independiente */}
              <div className="flex-1 overflow-y-auto">{children}</div>
            </main>

            <footer className="shrink-0 border-t p-2">footer</footer>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
